bachhoaxanhdemo/Controllers/CartController.cs
using bachhoaxanhdemo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace bachhoaxanhdemo.Controllers
{
    public class CartController : Controller
    {
        private const string CartSession = "CartSession";
        public BhxDbContext _dbBhx = new BhxDbContext();
        // GET: Cart
        public ActionResult Index()
        {
            var listCategories = _dbBhx.Categories.OrderBy(x => x.idCategory).ToList();
            var listTitle = _dbBhx.ProductTitles.OrderBy(x => x.idProductTitle).ToList();
            ViewBag.listCategories = listCategories;
            ViewBag.listTitle = listTitle;


            var cart = Session[CartSession];
            List<CardItem> list = new List<CardItem>();
            
            if (cart != null)
            {
                list = (List<CardItem>)cart;
            }
            return View(list);
        }

        public ActionResult AddItem(int? productId, int quantity)
        {
            var cart = Session[CartSession];
            var product = _dbBhx.Products.FirstOrDefault(x => x.idProduct == productId);
            var list = (List<CardItem>)cart;
            if (cart != null)
            {
                
                if (list.Exists(x => x.Product.idProduct == productId))
                {
                    foreach (var item in list)
                    {
                        if (item.Product.idProduct == productId)
                        {
                            item.Quantity += quantity;
                        }
                    }
                }
                else
                {
                    var item = new CardItem();
                    item.Product = product;
                    item.Quantity = quantity;
                    list.Add(item);

                }

            }
            else
            {
                //create new cart item
                var item = new CardItem();
                item.Product = product;
                item.Quantity = quantity;            
                list.Add(item);
                //assign list card item into session
                //Session[CartSession] = list;
                Session[CartSession] = list;

            }
            return View(list);
        }
    }
}

bachhoaxanhdemo/Controllers/ProductTitlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bachhoaxanhdemo.Models;

namespace bachhoaxanhdemo.Controllers
{
   
    public class ProductTitlesController : Controller
    {
        public BhxDbContext _dbBhx2 = new BhxDbContext();
        // GET: ProductTitles
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();       
            }
            var listCategories = _dbBhx2.Categories.OrderBy(x => x.idCategory).ToList();
            var listTitle = _dbBhx2.ProductTitles.OrderBy(x => x.idProductTitle).ToList();
            ViewBag.listCategories = listCategories;
            ViewBag.listTitle = listTitle;
            return View();
        }
        public ActionResult GroupFeatureProductByTitle(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            //var productTitle = _dbBhx.ProductTitles.Where(p => p.idProductTitle == id).ToList();
            List<Product> listProductByTitle = (from p in _dbBhx2.Products
                                                join pt in _dbBhx2.ProductTitles on p.idProductTitle equals pt.idProductTitle
                                                where p.idProductTitle == id
                                                select p).ToList();
            var productTitleName = _dbBhx2.ProductTitles.FirstOrDefault(x => x.idProductTitle == id).productTitleName;
            var ProductByTitle = new ProdByTitle();
            ProductByTitle.LIST_PRODUCT = listProductByTitle;
            ProductByTitle.ProductTitleName = productTitleName;         
            return View( ProductByTitle);
        }

    }
}

bachhoaxanhdemo/Views/Shared/GroupCategory.cshtml
<div class="groupcate">
    <div class="namegroup">
        Nhóm hàng thường mua
    </div>
    <div class="listgroup">
        @for (int i = 0; i < 2; i++)
        {
            <a href="/suatuoi">
                <img width="45" height="45" src="~/Content/image/sua-tuoi-202006021003313572.png" alt="sữa tươi" />
                <span>Sữa tươi</span>
            </a>
            <a href="/nuocngot">
                <img width="45" height="45" src="~/Content/image/nuoc-ngot-giai-khat-202006020939383550.png" alt="nước ngọt" />
                <span>Nước ngọt</span>
            </a>
            <a href="/khan-giay-uot">
                <img width="45" height="45" src="~/Content/image/khan-giay-uot-202006010858420776.png" alt="khăn giấy ướt" />
                <span>Khăn giấy ướt</span>
            </a>
            <a href="/hai-san-dong-lanh">
                <img width="45" height="45" src="~/Content/image/thit-hai-san-dong-lanh-201910311114302141.png" alt="hải sản đông lạnh" />
                <span>Thịt, hải sản, rau củ đông lạnh</span>
            </a>

            <a href="/nuoc-uong-co-con">
                <img width="45" height="45" src="~/Content/image/thit-hai-san-dong-lanh-201910311114302141.png" alt="bia" />
                <span>Bia, nước uống có cồn</span>
            </a>

        }
    </div>
</div>

bachhoaxanhdemo/Views/Shared/GroupFeatureFresh.cshtml
<div class="groupfeature groupfeaturefresh">
    <div class="banner">
        <img src="~/Content/image/stickFresh.png" alt="Thịt, cá, trứng, rau củ" />
        <div class="countproduct">
            <span class="totalproduct">311</span>
            <span class="text">sản phẩm</span>
        </div>
    </div>

    <div class="cate-list">
        <div class="cate-item">
            <span>
                Thịt, cá,
                <br />
                tôm, trứng
            </span>
        </div>
        <div class="cate-item">
            <span>
                Rau củ,
                <br />
                rau nêm
            </span>
        </div>

        <div class="cate-item">
            <span>
                Trái cây
            </span>
        </div>
        <div class="cate-item">
            <span>
                Thực phẩm
                <br />
                sơ chế sẵn
            </span>
        </div>
        <div class="cate-item">
            <span>
                Thực phẩm
                <br />
                đông lạnh
            </span>
        </div>

    </div>

    <ul class="cate cateproduct">
        @for (int i = 0; i < 4; i++)
        {
            <li class="product">
                <a href="#" title="Cải thìa túi 500g">
                    <div class="boximg center" title="Cải thìa túi 500g">
                        <img width="160" height="160" alt="Cải thìa túi 500g" src="https://cdn.tgdd.vn/Products/Images/8820/226913/bhx/cai-thia-tui-500g-202012120828339329_300x300.jpg" />
                    </div>
                    <div class="product-name">Cải thìa túi 500g</div>
                    <div class="price"><strong>19.000đ</strong></div>
                </a>
                <a class="buy">Chọn mua</a>
            </li>
        }

    </ul>

    <div class="viewmore noafter">
        Xem thêm 341 sản phẩm
    </div>
</div>

bachhoaxanhdemo/Views/Shared/Header.cshtml
    <header class="sticky">
        <div class="tophead">
            <a href="@Url.Action("Index", "Home")" class="header__logo" aria-hidden="true">
                <i class="bhx-logo"></i>
            </a>
            <div class="header__popup-overlays" style="display:none"></div>
            <div class="header__locationContainer">
                <div class="locationUser">
                    <div class="location_left">
                        <i class="bhx-toggle"></i>
                        <div class="current_locate">
                            <span class="shipto">Giao tại : </span>
                            <span class="shiptohere">Thành phố Hồ Chí Minh</span>
                            <span class="change">Thay đổi</span>
                        </div>
                        <div class="clr"></div>
                    </div>

                </div>
            </div>
            <div class="header__cart">
                <form class="mainsearch">
                    <div class="easy-autocomplete" style="width:385px">
                        <input type="text" autocomplete="off" placeholder="Anh tìm gì..." id="text-search" maxlength="80" aria-label="text-search" />
                    </div>
                    <div class="reset" style="display:none"><i class="bhx-closemenu"></i></div>
                    <button type="submit" aria-label="Search">
                        <i class="bhx-search" style="display: inline-block;"></i>
                        <div class="btn-search" style="display:none"><span>TÌM</span></div>
                    </button>

                </form>
                <a href="/lich-su-mua-hang" class="histories">
                    Đơn hàng
                    <br />
                    anh Tuấn
                </a>
                <a href="@Url.Action("Index", "Cart")"  class="temcart no">
                    <div>
                        <i class="bhx-cart" style="display:inline-block"></i>
                        <span class="hidden">0</span>
                    </div>
                    <div>
                        <b class="card">GIỎ HÀNG</b>
                        <b class="sumorder hidden">0 VND</b>
                    </div>
                </a>
            </div>
        </div>

        @* Html DANH MUC SAN PHAM *@
        <aside class="colmenu sb-container sb-container-noscroll">
            <div class="sb-scrollbar-container">
                <div class="sb-scrollbar" style="height:auto; top:auto"></div>
            </div>
            <div class="sb-content">
                <nav class="menu-hover">
                    <span class="span-header">
                        <i class="bhx-navmenu"></i>
                        DANH MỤC SẢN PHẨM
                    </span>
                    <ul class="colmenu-ul">
                        <li class="fourkfarm"><a href="/rau-an-toan-4kfarm">RAU AN TOÀN 4kFarm</a></li>

                        @foreach (var item in ViewBag.listCategories)
                        {
                            if (@item.idCategory != 1)
                            {
                                <li>
                                    <div class="nav-parent">@item.categoryName</div>
                                    <div class="nav-item">

                                        @foreach (var title in ViewBag.listTitle)
                                        {
                                            if (title.idCategory == item.idCategory)
                                            {
                                                <div class="parent">
                                                    <a href="@Url.Action("Index", "ProductTitles",new{ id = title.idProductTitle })" class="link-hover menu-haschild">@title.productTitleName</a>
                                                </div>
                                            }
                                        }



                                    </div>
                                </li>
                            }
                        }



                        <li class="nav-search">
                            <input type="search" class="search-menu" id="searchMenu" autocomplete="off" spellcheck="false" aria-label="Tìm món hàng" placeholder="Nhập món hàng cần tìm" />
                            <button class="show" type="button" aria-label="Search">
                                <i class="bhx-search"></i>
                            </button>
                        </li>
                        <li class="productpromo-count">
                            <a href="/khuyen-mai">
                                <i class="bhx-productpromo"></i>
                                <strong class="number">2.151</strong>
                                sản phẩm khuyến mãi
                            </a>
                        </li>
                        <li class="product-expired">
                            <a href="/khuyen-mai/xa-kho-gia-soc">
                                <i class="bhx-productexpired"></i>
                                Xả kho giá sốc
                            </a>
                        </li>
                        <li class="store-count">
                            <a href="/he-thong-sieu-thi">
                                <i class="bhx-storecount"></i>
                                Danh sách
                                <strong class="number">1.688</strong>
                                cửa hàng
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>
    </header>

bachhoaxanhdemo/Views/Shared/Section.cshtml
<section>
    <aside class="colcontent">
        @Html.Partial("SlideBanner")
        @Html.Partial("GroupCategory")
        @Html.Partial("GroupFeatureFresh")
        @Html.Partial("GroupFeatureProduct")
    </aside>
    <div class="clr"></div>
</section>

bachhoaxanhdemo/Views/Shared/SlideBanner.cshtml
<div class="slide-home owl-carousel owl-theme">

    @{
        for (int i = 1; i < 8; i++)
        {
            <a href="./" style="background: #007251">
                <img width="360" height="130" style="opacity:1;" src="~/Content/image/banner@{ @i }.jpg" />
            </a>
        }
    }

</div>

bachhoaxanhdemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href=@ViewBag.Logo />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">

    @*<link href=@ViewBag.Css rel="stylesheet" />*@
    <title>@ViewBag.Title</title>
    @*@Styles.Render("~/Content/css")*@
    @*@Styles.Render(ViewBag.Css)*@
    @*@Styles.Render("~/Content/owl.carousel")*@
    @RenderSection("heads", required: false)
</head>
<body class="new2020">

   
    @RenderBody()


    @RenderSection("scripts", required: false)
</body>
</html>

bachhoaxanhdemo/Views/Shared/footer.cshtml
<footer class="m-footer">
    <div class="main-footer">
        <div class="footer-order">
            <div class="footer-order-left">
                <i class="bhx-sship"></i>
                <p>
                    Đặt online
                    <b>
                        giao tận nhà ĐÚNG GIỜ
                    </b>
                    <br />
                    (nếu trễ đền 50.000₫)
                </p>
            </div>
            <div class="footer-order-right">
                <i class="bhx-swap"></i>
                <a href="https://www.bachhoaxanh.com/kinh-nghiem-hay/chinh-sach-doi-tra-1230736">

                    <p>
                        Đổi, trả sản phẩm <b>trong 7 ngày</b>
                    </p>
                </a>
            </div>
        </div>
        <div class="footer">
            <div class="detail">
                <div class="detail-left">
                    <div class="callcenter">
                        <i class="bhx-call"></i> Tổng đài: <a href="tel:19001908">1900.1908</a> - <a href="tel:02836229900">028.3622.9900</a> (7:00 - 21:30)
                    </div>
                    <div class="linkstatic">
                        <div class="link-1">
                            <a class="link link-footer" href="/chinh-sach-giao-hang">Chính sách giao hàng</a>
                            <a class="link link-footer" href="/kinh-nghiem-hay/chinh-sach-doi-tra-1230736">Chính sách đổi trả</a>
                            <a class="link link-footer" href="/lien-he">Liên hệ</a>
                        </div>


                        <div class="link-2">
                            <a class="link link-footer" href="/https://hddt.bachhoaxanh.com" target="_blank" rel="noopener">Hóa đơn điện tử</a>
                            <a class="link link-footer" href="/huong-dan-mua-hang">Hướng dẫn mua hàng</a>
                            <a class="link link-footer" href="/quy-che-hoat-dong">Quy chế hoạt động</a>
                        </div>
                        <div class="link-3">
                            <a class="recruitment link" href="https://vieclam.thegioididong.com" target="_blank" rel="noopener">Tuyển dụng </a>
                            <a class="link" href="https://vieclam.thegioididong.com" target="_blank" rel="noreferrer"><strong>8.401</strong> công việc đang chờ bạn</a>
                        </div>
                    </div>
                    <div class="logo-member">
                        <span>Website thành viên</span>
                        <div class="link-member">
                            <a href="https://www.thegioididong.com/" target="_blank" aria-hidden="true" rel="noopener"><i class="bhx-tgdd"></i></a>
                            <a href="https://www.dienmayxanh.com/" target="_blank" aria-hidden="true" rel="noopener"><i class="bhx-dmx"></i></a>
                            <a href="https://www.maiamtgdd.vn/" target="_blank" aria-hidden="true" rel="noopener"><i class="bhx-maiam"></i></a>
                        </div>
                    </div>
                </div>
                <div class="detail-right">
                    <div class="dki-product">
                        <i class="bhx-footer-purchase"></i>
                        <a href="/thu-mua-san-pham" class="purchaselink">Đăng ký chào hàng vào Bách Hóa Xanh</a>
                    </div>
                    <div class="bhx-stores">
                        <i class="bhx-store"></i><a href="/he-thong-sieu-thi">Hệ thống <span>1.693</span> cửa hàng Bách Hóa Xanh</a>
                    </div>
                    <div class="promotion">
                        7
                        <a href="/he-thong-sieu-thi#newstores">cửa hàng mới khai trương</a>
                        <div class="lab_promo">(Có khuyến mãi)</div>
                    </div>
                    <div class="stores-about-to-open">
                        5<a href="/he-thong-sieu-thi#comingstores">cửa hàng sắp khai trương</a>
                    </div>
                    <div class="social">
                        <a href="http://online.gov.vn/HomePage/CustomWebsiteDisplay.aspx?DocId=43376" target="_blank" class="bhx-bct" aria-hidden="true" rel="noopener"></a>
                        <a href="https://www.dmca.com/Protection/Status.aspx?ID=ef7c58db-1070-4726-9941-843b4ef9a243&amp;refurl=https://www.bachhoaxanh.com/" title="DMCA.com Protection Status" class="dmca-badge">
                            <img width="100" height="20" class="lazy initial loaded" data-src="https://images.dmca.com/Badges/dmca-badge-w100-5x1-11.png?ID=ef7c58db-1070-4726-9941-843b4ef9a243" alt="DMCA.com Protection Status" src="https://images.dmca.com/Badges/dmca-badge-w100-5x1-11.png?ID=ef7c58db-1070-4726-9941-843b4ef9a243" data-was-processed="true">
                        </a>
                        <iframe name="f7b10bf69f4624" height="1000px" data-testid="fb:like Facebook Social Plugin" title="fb:like Facebook Social Plugin" frameborder="0" allowtransparency="true" allowfullscreen="true" scrolling="no" allow="encrypted-media" src="https://www.facebook.com/v3.2/plugins/like.php?action=like&amp;app_id=369722380436915&amp;channel=https%3A%2F%2Fstaticxx.facebook.com%2Fx%2Fconnect%2Fxd_arbiter%2F%3Fversion%3D46%23cb%3Df39ba490b08db5%26domain%3Dwww.bachhoaxanh.com%26origin%3Dhttps%253A%252F%252Fwww.bachhoaxanh.com%252Ff1b38e4485d98a4%26relation%3Dparent.parent&amp;container_width=0&amp;href=https%3A%2F%2Fwww.facebook.com%2Fsieuthibachhoaxanh%2F&amp;layout=button_count&amp;locale=vi_VN&amp;sdk=joey&amp;share=false&amp;show_faces=false&amp;size=small&amp;width=90px" style="border: none; visibility: visible; width: 90px; height: 28px;" class=""></iframe>

                        <div class="yt-subscribe">

                            <span>YouTube</span>

                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>
    <div class="copyright">
        © 2018. Công Ty Cổ Phần Thương Mại Bách Hoá Xanh. GPDKKD: 0310471746 do sở KH &amp; ĐT TP.HCM cấp ngày 23/11/2010. Địa chỉ: 128 Trần Quang Khải, P. Tân Định, Q.1, TP.Hồ Chí Minh. Email:lienhe@bachhoaxanh.com Chịu trách nhiệm nội dung: Trần Nhật Linh.
        <a href="/quy-che-hoat-dong">Xem chính sách sử dụng web</a>
    </div>

</footer>
<div class="feedback">
    <i class="img-feedback">
    </i>
</div>
<div class="backtop">
    ↑<br />
    lên đầu trang
</div>
<div class="popup-cmt" style="display:none;">
    <div class="confirm-cmt">
        <h1 class="title-cmt">
            Bách hoá xanh xin hân hạnh được hỗ trợ quý khách
        </h1>
        <form id="frmContact" onsubmit="return SubmitContact('#frmContact')" method="post">
            <div class="js-float-label-wrapper">
                <textarea name="txtContent" class="txtContent" rows="3" placeholder="Nội dung (xin quý khách mô tả chi tiết)"></textarea>
            </div>
            <div class="gendercomment">
                <input type="radio" name="gendercmt" /> Anh
                <input type="radio" name="gendercmt" /> Chi
            </div>
            <input class="fullname" type="text" name="txtFullName" placeholder="Họ và tên của quý khách">
            <input class="phone-number" type="number" placeholder="Nhập số điện thoại (khi cần BachhoaXANH gọi lại)" maxlength="11">
            <input class="email" type="text" name="txtEmail" placeholder="Email của quý khách">

            <input type="hidden" name="txtSex" value="1">
            <div class="contact-vvbtn">
                <button class="submit-cmt" title="Gửi góp ý cho Bách hóa Xanh" type="submit">Gửi góp ý</button>
            </div>
            <div class="close-cmt">
                Đóng 
            </div>
        </form>

    </div>
</div>

bachhoaxanhdemo/Views/Shared/group.cshtml
<div class="groupcate">
    <div class="namegroup">Nhóm hàng thường mua</div>
    <div class="box-listgroup">
        <div class="listgroup listgroup-up">
            <a href="/cu">
                <img width="45" class="lazy initial loaded" height="45" data-src="//cdn.tgdd.vn/Products/Images/8785/bhx/cu-qua-202010011028494832.jpg" alt="Củ, quả" src="//cdn.tgdd.vn/Products/Images/8785/bhx/cu-qua-202010011028494832.jpg" data-was-processed="true">
                <span>Củ, quả</span>
            </a>
            <a href="/rau-sach">
                <img width="45" class="lazy initial loaded" height="45" data-src="//cdn.tgdd.vn/Products/Images/8820/bhx/rau-202010011029145459.jpg" alt="Rau" src="//cdn.tgdd.vn/Products/Images/8820/bhx/rau-202010011029145459.jpg" data-was-processed="true">
                <span>Rau</span>
            </a>
            <a href="/hanh-toi-tac-me-rau-nem">
                <img width="45" class="lazy initial loaded" height="45" data-src="//cdn.tgdd.vn/Products/Images/8786/bhx/hanh-toi-tac-me-rau-nem-202010011028268990.jpg" alt="Hành, tỏi, tắc, me, rau nêm" src="//cdn.tgdd.vn/Products/Images/8786/bhx/hanh-toi-tac-me-rau-nem-202010011028268990.jpg" data-was-processed="true">
                <span>Hành, tỏi, tắc, me, rau nêm</span>
            </a>
            <a href="/dau-goi">
                <img width="45" class="lazy initial loaded" height="45" data-src="//cdn.tgdd.vn/Products/Images/2483/bhx/dau-goi-202006021004286121.png" alt="Dầu gội" src="//cdn.tgdd.vn/Products/Images/2483/bhx/dau-goi-202006021004286121.png" data-was-processed="true">
                <span>Dầu gội</span>
            </a>
            <a href="/bot-giat">
                <img width="45" class="lazy initial loaded" height="45" data-src="//cdn.tgdd.vn/Products/Images/2463/bhx/bot-giat-202006021112004707.png" alt="Bột giặt" src="//cdn.tgdd.vn/Products/Images/2463/bhx/bot-giat-202006021112004707.png" data-was-processed="true">
                <span>Bột giặt</span>
            </a>
        </div>
        <div class="listgroup listgroup-down">
            <a href="/bot-ngot">
                <img width="45" class="lazy initial loaded" height="45" data-src="//cdn.tgdd.vn/Products/Images/2805/bhx/bot-ngot-202006021100317011.png" alt="Bột ngọt" src="//cdn.tgdd.vn/Products/Images/2805/bhx/bot-ngot-202006021100317011.png" data-was-processed="true">
                <span>Bột ngọt</span>
            </a>
            <a href="/trai-cay-noi">
                <img width="45" class="lazy initial loaded" height="45" data-src="//cdn.tgdd.vn/Products/Images/8788/bhx/trai-cay-202011230929565950.png" alt="Trái cây" src="//cdn.tgdd.vn/Products/Images/8788/bhx/trai-cay-202011230929565950.png" data-was-processed="true">
                <span>Trái cây</span>
            </a>
            <a href="/ca-tom-muc-ech">
                <img width="45" class="lazy initial loaded" height="45" data-src="//cdn.tgdd.vn/Products/Images/8782/bhx/ca-tom-muc-ech-202010010934144850.png" alt="Cá, tôm, mực, ếch" src="//cdn.tgdd.vn/Products/Images/8782/bhx/ca-tom-muc-ech-202010010934144850.png" data-was-processed="true">
                <span>Cá, tôm, mực, ếch</span>
            </a>
            <a href="/thit-ga">
                <img width="45" class="lazy initial loaded" height="45" data-src="//cdn.tgdd.vn/Products/Images/8790/bhx/thit-ga-thit-vit-chim-cut-202010011030546959.jpg" alt="Thịt gà, thịt vịt, chim cút" src="//cdn.tgdd.vn/Products/Images/8790/bhx/thit-ga-thit-vit-chim-cut-202010011030546959.jpg" data-was-processed="true">
                <span>Thịt gà, thịt vịt, chim cút</span>
            </a>
            <a href="/sua-tuoi">
                <img width="45" class="lazy initial loaded" height="45" data-src="//cdn.tgdd.vn/Products/Images/2386/bhx/sua-tuoi-202006021003313572.png" alt="Sữa tươi" src="//cdn.tgdd.vn/Products/Images/2386/bhx/sua-tuoi-202006021003313572.png" data-was-processed="true">
                <span>Sữa tươi</span>
            </a>
        </div>

    </div>
</div>

bachhoaxanhdemo/Views/Shared/popup-feedback.cshtml
<div class="popup-cmt" style="display:none;">
    <div class="confirm-cmt">
        <h1 class="title-cmt">
            Bách hoá xanh xin hân hạnh được hỗ trợ quý khách
        </h1>
        <form id="frmContact" onsubmit="return SubmitContact('#frmContact')" method="post">
            <div class="js-float-label-wrapper">
                <textarea name="txtContent" class="txtContent" rows="3" placeholder="Nội dung (xin quý khách mô tả chi tiết)"></textarea>
            </div>
            <div class="gendercomment">
                <input type="radio" name="gendercmt" /> Anh
                <input type="radio" name="gendercmt" /> Chi
            </div>
            <input class="fullname" type="text" name="txtFullName" placeholder="Họ và tên của quý khách">
            <input class="phone-number" type="number" placeholder="Nhập số điện thoại (khi cần BachhoaXANH gọi lại)" maxlength="11">
            <input class="email" type="text" name="txtEmail" placeholder="Email của quý khách">

            <input type="hidden" name="txtSex" value="1">
            <div class="contact-vvbtn">
                <button class="submit-cmt" title="Gửi góp ý cho Bách hóa Xanh" type="submit">Gửi góp ý</button>
            </div>
            <div class="close-cmt">
                Đóng
            </div>
        </form>

    </div>
</div>