bachhoaxanhdemo/Models/ProductTitle.cs
namespace bachhoaxanhdemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("ProductTitle")]
    public partial class ProductTitle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductTitle()
        {
            Products = new HashSet<Product>();
        }

        [Key]
        public int idProductTitle { get; set; }

        [StringLength(50)]
        public string productTitleName { get; set; }

        public int? idCategory { get; set; }

        public virtual Category Category { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}

bachhoaxanhdemo/Controllers/DetailProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bachhoaxanhdemo.Models;

namespace bachhoaxanhdemo.Controllers
{

    public class DetailProductController : Controller
    {
        public BhxDbContext _dbBhx2 = new BhxDbContext();

        // GET: DetailProduct
        public ActionResult indexDetail(int? id, int? idProd)
        {
            if (id == null && idProd == null)
            {
                return HttpNotFound();
            }
            var listCategories = _dbBhx2.Categories.OrderBy(x => x.idCategory).ToList();
            var listTitle = _dbBhx2.ProductTitles.OrderBy(x => x.idProductTitle).ToList();
            ViewBag.listCategories = listCategories;
            ViewBag.listTitle = listTitle;
            ViewData["productDetails"] = _dbBhx2.Products.Where(p => p.idProductTitle == id).FirstOrDefault(x => x.idProduct == idProd);

            return View();
        }
        public ActionResult infodetails(int? id, int? idProd)
        {
            if (id == null && idProd == null)
            {
                return HttpNotFound();

            }
         
            var productDetails = _dbBhx2.Products.Where(p => p.idProductTitle == id).FirstOrDefault(x => x.idProduct == idProd);
            return View(productDetails);
        }

        public ActionResult ProductDetail(int? id, int? idProd)
        {
            if (id == null && idProd == null)
            {
                return HttpNotFound();
            }
            var productDetails = _dbBhx2.Products.Where(p => p.idProductTitle == id).FirstOrDefault(x => x.idProduct == idProd);
            return View(productDetails);
        }

    }
}

bachhoaxanhdemo/Controllers/ProductTitleController.cs
using bachhoaxanhdemo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace bachhoaxanhdemo.Controllers
{
    public class ProductTitleController : Controller
    {
        public bhxEntities _dbBhx = new bhxEntities();

        // GET: ProductTitle
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            var listCategories = _dbBhx.Categories.OrderBy(x => x.idCategory).ToList();
            var listTitle = _dbBhx.ProductTitles.OrderBy(x => x.idProductTitle).ToList();
            ViewBag.listCategories = listCategories;
            ViewBag.listTitle = listTitle;

            return View();
        }

        public ActionResult GroupFeatureProductByTitle(int? id)
        {

            if (id == null)
            {
                return HttpNotFound();
            }
            //var productTitle = _dbBhx.ProductTitles.Where(p => p.idProductTitle == id).ToList();
            List<Product> listProductByTitle = (from p in _dbBhx.Products
                                                join pt in _dbBhx.ProductTitles on p.idProductTitle equals pt.idProductTitle
                                                where p.idProductTitle == id
                                                select p).ToList();
            var productTitleName = _dbBhx.ProductTitles.FirstOrDefault(x => x.idProductTitle == id).productTitleName;

            var PRODUCTBYTITLE = new _ProdByTitle();
            PRODUCTBYTITLE.LIST_PRODUCT = listProductByTitle;
            PRODUCTBYTITLE.ProductTitleName = productTitleName;

            return View(PRODUCTBYTITLE);
        }
    }
}

bachhoaxanhdemo/Controllers/ProductTitlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bachhoaxanhdemo.Models;

namespace bachhoaxanhdemo.Controllers
{
   
    public class ProductTitlesController : Controller
    {
        public BhxDbContext _dbBhx2 = new BhxDbContext();
        // GET: ProductTitles
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();       
            }
            var listCategories = _dbBhx2.Categories.OrderBy(x => x.idCategory).ToList();
            var listTitle = _dbBhx2.ProductTitles.OrderBy(x => x.idProductTitle).ToList();
            ViewBag.listCategories = listCategories;
            ViewBag.listTitle = listTitle;
            return View();
        }
        public ActionResult GroupFeatureProductByTitle(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            //var productTitle = _dbBhx.ProductTitles.Where(p => p.idProductTitle == id).ToList();
            List<Product> listProductByTitle = (from p in _dbBhx2.Products
                                                join pt in _dbBhx2.ProductTitles on p.idProductTitle equals pt.idProductTitle
                                                where p.idProductTitle == id
                                                select p).ToList();
            var productTitleName = _dbBhx2.ProductTitles.FirstOrDefault(x => x.idProductTitle == id).productTitleName;
            var ProductByTitle = new ProdByTitle();
            ProductByTitle.LIST_PRODUCT = listProductByTitle;
            ProductByTitle.ProductTitleName = productTitleName;         
            return View( ProductByTitle);
        }

    }
}

bachhoaxanhdemo/Views/ProductTitles/GroupFeatureProductByTitle.cshtml
@model bachhoaxanhdemo.Models.ProdByTitle
@{
    ViewBag.Title = "GroupFeatureProductByTitle";
    Layout = null;
}

<div class="groupfeature">
    <h2 class="hometitle">
        @Model.ProductTitleName
    </h2>
    <ul class="cate cateproduct" id="catenow">
        @foreach (var item in Model.LIST_PRODUCT)
        {
        <li class="product">
            <a href="@Url.Action("indexDetail", "DetailProduct", new { id = item.idProductTitle, idProd = item.idProduct })" title="Cải thìa túi 500g">
                <div class="boximg center" title="Cải thìa túi 500g">
                    <img width="160" height="160" alt="bg-Lốc 4 hộp sữa tiệt trùng Dutch Lady 170ml" src=@(item.image != null ? item.image.Split(' ')[0] : "https://cdn.tgdd.vn/Products/Images/2943/229508/bhx/thung-16-hop-sua-dau-nanh-dau-den-oc-cho-hanh-nhan-yaho-190ml-202011060932118206_300x300.jpg") />
                </div>
                <div class="product-name">@(item.productName ?? item.productName)</div>
                <div class="price">
                    <span>42.000đ</span>
                    <strong>@(item.productPrice?.ToString("#,##0 đ"))</strong>
                    <label>-24%</label>
                </div>
            </a>
            <a class="buy">Chọn mua</a>
        </li>
        }

    </ul>


    <div class="viewmore noafter" id="loadMore">
        Xem thêm <span>2</span> sản phẩm khuyến mãi
        <span>
            <img id="loading" style="display: none;" src="~/Content/image/Spinner-1s-200px.gif" />
        </span>
    </div>
    <div class="cate-prom">
        <a class="hidden" href="sua-tuoi">Sữa tươi</a>
        <a class="hidden" href="sua-chua">Sữa chua</a>
        <a class="hidden" href="sua-ca-cao">Sữa ca cao</a>
    </div>
</div>

bachhoaxanhdemo/Views/ProductTitles/Index.cshtml
@{
    ViewBag.Title = "Siêu thị Bách hóa XANH - Mua bán thực phẩm, sản phẩm gia đình";
    ViewBag.Logo = "../Content/image/favicon.ico";
    ViewBag.Css = "~/Content/homecss";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

@section heads
{
    @Styles.Render("~/Content/homecss")
}


@Html.Partial("Header")

<section>
    <aside class="colcontent">

        @Html.Action("GroupFeatureProductByTitle")

    </aside>
    <div class="clr"></div>
</section>

@Html.Partial("footer")
@Scripts.Render("~/bundles/jquery")